SEO and accessibility adjustment
WildCodeSchool/2023-09-PHP-LYON-P3-eclat-d-art pull request #27
Opened 2024-01-09 11:13 UTC by victorzanotelli

J'ai changé le nom de la PR pour qu'il correspond aux changements que j'ai fait : Ajout des "aria label" + <meta description "">

2024-01-09 11:57 UTC, R-Ztr approved these changes

2024-01-09 12:01 UTC, Altyrion69 approved these changes

2024-01-09 15:30 UTC, StoicFrenchDev requested changes

2024-01-09 15:30 UTC, StoicFrenchDev commented on templates/artwork/show.html.twig
> +{# <div class="slider-css-target">
Dead code

2024-01-10 14:13 UTC, Guadanino approved these changes

2024-01-10 14:26 UTC, StoicFrenchDev approved these changes

2024-01-10 14:26 UTC, merged