Us08 s3 front page artist/index
WildCodeSchool/2023-09-PHP-LYON-P3-eclat-d-art pull request #38
Opened 2024-01-11 15:05 UTC by R-Ztr

2024-01-11 15:39 UTC, Altyrion69 approved these changes

2024-01-11 15:49 UTC, victorzanotelli approved these changes

2024-01-11 16:10 UTC, StoicFrenchDev requested changes

2024-01-11 16:10 UTC, StoicFrenchDev commented on templates/home/index.html.twig
> +                        <a href="user" aria-label="Discover more about this artist">Découvrir</a>					</div>
Use a path instead

2024-01-12 08:39 UTC, StoicFrenchDev approved these changes

2024-01-12 08:40 UTC, merged