Us22 s3 make random caroussel
WildCodeSchool/2023-09-PHP-LYON-P3-eclat-d-art pull request #40
Opened 2024-01-11 15:55 UTC by R-Ztr

2024-01-11 16:14 UTC, Guadanino approved these changes

2024-01-11 18:09 UTC, Altyrion69 approved these changes

2024-01-12 07:55 UTC, StoicFrenchDev requested changes

2024-01-12 07:55 UTC, StoicFrenchDev commented on templates/home/index.html.twig
> +<h2><a href="user">Artistes</a></h2>
For the sake of unifornity, use a path for the links.

2024-01-12 08:31 UTC, StoicFrenchDev commented
Doubon

2024-01-12 08:31 UTC, closed without merging