Us35 s04 admin dashboard
WildCodeSchool/2023-09-PHP-LYON-P3-eclat-d-art pull request #58
Opened 2024-01-24 14:03 UTC by victorzanotelli

2024-01-24 14:04 UTC, Guadanino approved these changes

2024-01-24 14:06 UTC, R-Ztr approved these changes

2024-01-24 14:59 UTC, StoicFrenchDev requested changes
Clean the dead code, and verify if you need the queries from the UserRepository.

2024-01-24 14:59 UTC, StoicFrenchDev commented on src/Controller/Admin/CategoryCrudController.php
> +    public function configureFields(string $pageName): iterable
dead code

2024-01-24 14:59 UTC, StoicFrenchDev commented on src/Controller/Admin/UserCrudController.php
> +    {
dead code

2024-01-24 14:59 UTC, StoicFrenchDev commented on src/Repository/UserRepository.php
> +    public function findByExampleField(string $value): array
Are you using this method? If yes choose a different name

2024-01-24 14:59 UTC, StoicFrenchDev commented on src/Repository/UserRepository.php
> +    public function findOneBySomeField(string $value): ?User
Same goes for this one. If not remove them

2024-01-24 15:14 UTC, victorzanotelli commented
> Clean the dead code, and verify if you need the queries from the UserRepository.

Thanks for your review, i finish what i'm doing rn and i'll fix it asap

2024-01-25 12:41 UTC, StoicFrenchDev approved these changes

2024-01-25 12:41 UTC, merged