Us03 s1 home page
WildCodeSchool/2023-09-PHP-LYON-P3-eclat-d-art pull request #7
Opened 2023-12-15 15:38 UTC by Altyrion69

2023-12-15 15:39 UTC, R-Ztr approved these changes

2023-12-15 15:40 UTC, victorzanotelli approved these changes

2023-12-15 15:41 UTC, Guadanino approved these changes

2023-12-15 16:12 UTC, StoicFrenchDev requested changes

2023-12-15 16:12 UTC, StoicFrenchDev commented on templates/home/index.html.twig
> +<div id="card-area">
Duplicated id

2023-12-17 00:52 UTC, Altyrion69 reviewed
id is change. Only 1 id

2023-12-17 00:54 UTC, Altyrion69 commented on templates/home/index.html.twig
> +<div id="card-area">
id change

2023-12-17 08:38 UTC, StoicFrenchDev approved these changes

2023-12-17 08:38 UTC, merged